import type { Movie, MoodConfig } from '@/types'

// ─── Mood Configuration ───────────────────────────────────────────────────────

export const MOOD_CONFIG: MoodConfig[] = [
  {
    id: 'relaxed',
    label: 'Relaxed',
    emoji: '😌',
    description: 'Cozy, feel-good, easy watching',
    gradient: 'from-green-400 to-teal-500',
    textColor: 'text-green-400',
  },
  {
    id: 'playful',
    label: 'Playful',
    emoji: '😂',
    description: 'Laugh-out-loud comedies & fun adventures',
    gradient: 'from-yellow-400 to-orange-400',
    textColor: 'text-yellow-400',
  },
  {
    id: 'emotional',
    label: 'Emotional',
    emoji: '😢',
    description: 'Moving dramas that touch the heart',
    gradient: 'from-blue-400 to-indigo-500',
    textColor: 'text-blue-400',
  },
  {
    id: 'thrilled',
    label: 'Thrilled',
    emoji: '😱',
    description: 'Edge-of-your-seat tension & horror',
    gradient: 'from-red-500 to-rose-600',
    textColor: 'text-red-400',
  },
  {
    id: 'adventurous',
    label: 'Adventurous',
    emoji: '🗺️',
    description: 'Epic journeys & action-packed stories',
    gradient: 'from-amber-400 to-yellow-500',
    textColor: 'text-amber-400',
  },
  {
    id: 'romantic',
    label: 'Romantic',
    emoji: '💕',
    description: 'Love stories & heartfelt connections',
    gradient: 'from-pink-400 to-rose-400',
    textColor: 'text-pink-400',
  },
  {
    id: 'inspired',
    label: 'Inspired',
    emoji: '💡',
    description: 'Motivating biopics & stories of triumph',
    gradient: 'from-violet-400 to-purple-500',
    textColor: 'text-violet-400',
  },
  {
    id: 'nostalgic',
    label: 'Nostalgic',
    emoji: '🕰️',
    description: 'Timeless classics from the past',
    gradient: 'from-orange-400 to-amber-500',
    textColor: 'text-orange-400',
  },
  {
    id: 'curious',
    label: 'Curious',
    emoji: '🔍',
    description: 'Mysteries, puzzles & mind-benders',
    gradient: 'from-cyan-400 to-blue-500',
    textColor: 'text-cyan-400',
  },
  {
    id: 'dark',
    label: 'Dark',
    emoji: '🌑',
    description: 'Noir, psychological & unsettling tales',
    gradient: 'from-slate-500 to-gray-700',
    textColor: 'text-slate-400',
  },
]

// ─── Mock Movie Data (50 Films) ───────────────────────────────────────────────

export const MOCK_MOVIES: Movie[] = [
  // ── RELAXED ────────────────────────────────────────────────────────────────
  {
    id: 244572,
    title: 'Chef',
    year: 2014,
    rating: 7.3,
    voteCount: 120000,
    duration: 114,
    genres: ['Comedy', 'Drama'],
    moods: ['relaxed', 'inspired', 'playful'],
    synopsis:
      'A chef who loses his restaurant job starts up a food truck in an effort to reclaim his creative promise, while trying to reconnect with his ex-wife and son.',
    posterPath: '/1LX4mHLnP6kSaJSnkYqBiRXbHjr.jpg',
    trailerKey: 'v1GKtTFDCmM',
    cast: ['Jon Favreau', 'Sofia Vergara', 'John Leguizamo'],
    director: 'Jon Favreau',
    platforms: ['Netflix', 'Prime Video'],
    isHiddenGem: false,
    popularityScore: 65,
    language: 'en',
  },
  {
    id: 209112,
    title: 'Julie & Julia',
    year: 2009,
    rating: 7.0,
    voteCount: 180000,
    duration: 123,
    genres: ['Drama', 'Biography', 'Comedy'],
    moods: ['relaxed', 'inspired'],
    synopsis:
      'Julia Child\'s early life in 1950s Paris, as well as a young New Yorker who aspires to cook all 524 recipes from Child\'s cookbook.',
    posterPath: '/mze7vPe08YiKBvJcMGi0eeXSwqx.jpg',
    trailerKey: 'TlHKXhMdx8s',
    cast: ['Meryl Streep', 'Amy Adams', 'Stanley Tucci'],
    director: 'Nora Ephron',
    platforms: ['Netflix'],
    isHiddenGem: false,
    popularityScore: 60,
    language: 'en',
  },
  {
    id: 153518,
    title: 'The Secret Life of Walter Mitty',
    year: 2013,
    rating: 7.3,
    voteCount: 360000,
    duration: 114,
    genres: ['Adventure', 'Comedy', 'Drama'],
    moods: ['relaxed', 'adventurous', 'inspired'],
    synopsis:
      'When his job along with that of his co-worker are threatened, Walter takes action in the real world embarking on a globe-trotting journey.',
    posterPath: '/obZau4dPCZXdPDxCeHGiZRkRiEX.jpg',
    trailerKey: 'bHqjMhTudAE',
    cast: ['Ben Stiller', 'Kristen Wiig', 'Adam Scott'],
    director: 'Ben Stiller',
    platforms: ['Disney+', 'Prime Video'],
    isHiddenGem: false,
    popularityScore: 68,
    language: 'en',
  },
  {
    id: 508439,
    title: 'Soul',
    year: 2020,
    rating: 8.1,
    voteCount: 580000,
    duration: 100,
    genres: ['Animation', 'Family', 'Comedy', 'Drama'],
    moods: ['relaxed', 'emotional', 'inspired'],
    synopsis:
      'A musician who has lost his passion for music is transported out of his body and must find his way back with the help of an unborn soul.',
    posterPath: '/hm58fFDtOhaQuBMZqwKqhJpOXLl.jpg',
    trailerKey: 'xOsLIiBStEs',
    cast: ['Jamie Foxx', 'Tina Fey', 'Graham Norton'],
    director: 'Pete Docter',
    platforms: ['Disney+'],
    isHiddenGem: false,
    popularityScore: 84,
    language: 'en',
  },

  // ── PLAYFUL ────────────────────────────────────────────────────────────────
  {
    id: 120467,
    title: 'The Grand Budapest Hotel',
    year: 2014,
    rating: 8.1,
    voteCount: 780000,
    duration: 99,
    genres: ['Comedy', 'Drama', 'Crime'],
    moods: ['playful', 'nostalgic', 'curious'],
    synopsis:
      'A writer encounters the owner of an aging European hotel, who tells him of his glorious years serving as a lobby boy under an eccentric concierge.',
    posterPath: '/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg',
    trailerKey: 'JfyA3UUVZ7M',
    cast: ['Ralph Fiennes', 'Tony Revolori', 'Saoirse Ronan'],
    director: 'Wes Anderson',
    platforms: ['Disney+', 'Prime Video'],
    isHiddenGem: false,
    popularityScore: 82,
    language: 'en',
  },
  {
    id: 375262,
    title: 'Game Night',
    year: 2018,
    rating: 7.0,
    voteCount: 270000,
    duration: 100,
    genres: ['Comedy', 'Mystery', 'Action'],
    moods: ['playful', 'curious'],
    synopsis:
      'A group of friends who meet regularly for game nights find themselves in a real-life mystery when one is kidnapped by criminals.',
    posterPath: '/jTOT3OHKlvE0qWjEEYLZuE9bMLF.jpg',
    trailerKey: 'VRwvkBTF7CU',
    cast: ['Jason Bateman', 'Rachel McAdams', 'Billy Magnussen'],
    director: 'John Francis Daley',
    platforms: ['Netflix', 'HBO Max'],
    isHiddenGem: false,
    popularityScore: 70,
    language: 'en',
  },
  {
    id: 2493,
    title: 'The Princess Bride',
    year: 1987,
    rating: 8.0,
    voteCount: 340000,
    duration: 98,
    genres: ['Adventure', 'Comedy', 'Romance', 'Fantasy'],
    moods: ['playful', 'romantic', 'nostalgic', 'adventurous'],
    synopsis:
      'A grandfather reads his sick grandson a fairy tale involving a beautiful girl, the man who loves her, and a dangerous villain.',
    posterPath: '/lBnZGKHxCikKGlPPuF9R7mfATB9.jpg',
    trailerKey: 'VYgcrny2hRs',
    cast: ['Cary Elwes', 'Robin Wright', 'Mandy Patinkin'],
    director: 'Rob Reiner',
    platforms: ['Disney+'],
    isHiddenGem: false,
    popularityScore: 74,
    language: 'en',
  },
  {
    id: 64635,
    title: 'Crazy, Stupid, Love',
    year: 2011,
    rating: 7.4,
    voteCount: 480000,
    duration: 118,
    genres: ['Comedy', 'Drama', 'Romance'],
    moods: ['playful', 'romantic', 'emotional'],
    synopsis:
      'A middle-aged man, hurt by his wife\'s infidelity, gets help from a younger man to reinvent himself and rediscover his manhood.',
    posterPath: '/hm6NNKcAqkBwmAJ0K1K2T2t0HKW.jpg',
    trailerKey: 'zBF3EHQaE3E',
    cast: ['Steve Carell', 'Ryan Gosling', 'Emma Stone'],
    director: 'Glenn Ficarra',
    platforms: ['Netflix', 'Prime Video'],
    isHiddenGem: false,
    popularityScore: 72,
    language: 'en',
  },

  // ── EMOTIONAL ─────────────────────────────────────────────────────────────
  {
    id: 14534,
    title: 'The Pursuit of Happyness',
    year: 2006,
    rating: 8.0,
    voteCount: 730000,
    duration: 117,
    genres: ['Drama', 'Biography'],
    moods: ['emotional', 'inspired'],
    synopsis:
      'Based on the true story of Chris Gardner\'s journey from homelessness to becoming a successful stockbroker while being a single father.',
    posterPath: '/kj3F8tGSGvqBVP1oNdXnVNUX4sC.jpg',
    trailerKey: '89Kq2isDnng',
    cast: ['Will Smith', 'Jaden Smith', 'Thandiwe Newton'],
    director: 'Gabriele Muccino',
    platforms: ['Netflix', 'Prime Video'],
    isHiddenGem: false,
    popularityScore: 80,
    language: 'en',
  },
  {
    id: 453,
    title: 'A Beautiful Mind',
    year: 2001,
    rating: 8.2,
    voteCount: 580000,
    duration: 135,
    genres: ['Drama', 'Biography'],
    moods: ['emotional', 'inspired', 'curious'],
    synopsis:
      'The story of Nobel Prize-winning mathematician John Nash and his struggle with paranoid schizophrenia.',
    posterPath: '/zwzWCmH72OSC9NA0ipoqhbhhbWj.jpg',
    trailerKey: '5hgF_S7nWqk',
    cast: ['Russell Crowe', 'Ed Harris', 'Jennifer Connelly'],
    director: 'Ron Howard',
    platforms: ['Prime Video', 'HBO Max'],
    isHiddenGem: false,
    popularityScore: 77,
    language: 'en',
  },
  {
    id: 10515,
    title: 'Up',
    year: 2009,
    rating: 8.3,
    voteCount: 890000,
    duration: 96,
    genres: ['Animation', 'Adventure', 'Comedy', 'Drama'],
    moods: ['emotional', 'adventurous', 'playful'],
    synopsis:
      'An elderly man fulfills his lifelong dream of seeing the wilds of South America by tying thousands of balloons to his house and floating away.',
    posterPath: '/kc3M04QQAuZ9woV8sPRuQFQlKP6.jpg',
    trailerKey: 'pkqDkm8P7fQ',
    cast: ['Edward Asner', 'Jordan Nagai', 'John Ratzenberger'],
    director: 'Pete Docter',
    platforms: ['Disney+'],
    isHiddenGem: false,
    popularityScore: 86,
    language: 'en',
  },
  {
    id: 424,
    title: "Schindler's List",
    year: 1993,
    rating: 9.0,
    voteCount: 1200000,
    duration: 195,
    genres: ['Drama', 'History', 'War'],
    moods: ['emotional', 'dark', 'inspired'],
    synopsis:
      'In German-occupied Poland, industrialist Oskar Schindler becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.',
    posterPath: '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
    trailerKey: 'gG22XNhtnoY',
    cast: ['Liam Neeson', 'Ralph Fiennes', 'Ben Kingsley'],
    director: 'Steven Spielberg',
    platforms: ['Peacock', 'Prime Video'],
    isHiddenGem: false,
    popularityScore: 88,
    language: 'en',
  },

  // ── THRILLED ───────────────────────────────────────────────────────────────
  {
    id: 419430,
    title: 'Get Out',
    year: 2017,
    rating: 7.7,
    voteCount: 740000,
    duration: 104,
    genres: ['Horror', 'Mystery', 'Thriller'],
    moods: ['thrilled', 'curious', 'dark'],
    synopsis:
      'A young African-American man visits his white girlfriend\'s parents for the weekend, but something unsettling creeps in.',
    posterPath: '/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg',
    trailerKey: 'DzfpyUB60YY',
    cast: ['Daniel Kaluuya', 'Allison Williams', 'Bradley Whitford'],
    director: 'Jordan Peele',
    platforms: ['Peacock', 'Prime Video'],
    isHiddenGem: false,
    popularityScore: 79,
    language: 'en',
  },
  {
    id: 274,
    title: 'The Silence of the Lambs',
    year: 1991,
    rating: 8.6,
    voteCount: 1300000,
    duration: 118,
    genres: ['Crime', 'Drama', 'Thriller'],
    moods: ['thrilled', 'curious', 'dark'],
    synopsis:
      'A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.',
    posterPath: '/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg',
    trailerKey: 'W6Mm8Sbe__o',
    cast: ['Jodie Foster', 'Anthony Hopkins', 'Scott Glenn'],
    director: 'Jonathan Demme',
    platforms: ['Netflix', 'Prime Video'],
    isHiddenGem: false,
    popularityScore: 85,
    language: 'en',
  },
  {
    id: 210577,
    title: 'Gone Girl',
    year: 2014,
    rating: 8.1,
    voteCount: 1200000,
    duration: 149,
    genres: ['Drama', 'Mystery', 'Thriller'],
    moods: ['thrilled', 'dark', 'curious'],
    synopsis:
      'With his wife\'s disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it\'s suspected that he may not be innocent.',
    posterPath: '/kov4Onkrv6YPQR3o7agPTSniIFJ.jpg',
    trailerKey: '4VYJnByBrpc',
    cast: ['Ben Affleck', 'Rosamund Pike', 'Neil Patrick Harris'],
    director: 'David Fincher',
    platforms: ['Max', 'Prime Video'],
    isHiddenGem: false,
    popularityScore: 82,
    language: 'en',
  },
  {
    id: 335797,
    title: 'A Quiet Place',
    year: 2018,
    rating: 7.5,
    voteCount: 640000,
    duration: 90,
    genres: ['Horror', 'Drama', 'Science Fiction'],
    moods: ['thrilled', 'emotional'],
    synopsis:
      'In a post-apocalyptic world, a family is forced to live in silence while hiding from monsters with ultra-sensitive hearing.',
    posterPath: '/nAU74GmpUk7t5iklEp3bufwDq4n.jpg',
    trailerKey: 'WR7cc5t7tv8',
    cast: ['Emily Blunt', 'John Krasinski', 'Millicent Simmonds'],
    director: 'John Krasinski',
    platforms: ['Paramount+', 'Prime Video'],
    isHiddenGem: false,
    popularityScore: 76,
    language: 'en',
  },

  // ── ADVENTUROUS ────────────────────────────────────────────────────────────
  {
    id: 157336,
    title: 'Interstellar',
    year: 2014,
    rating: 8.6,
    voteCount: 1600000,
    duration: 169,
    genres: ['Adventure', 'Drama', 'Science Fiction'],
    moods: ['adventurous', 'curious', 'emotional'],
    synopsis:
      'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
    posterPath: '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    trailerKey: 'zSWdZVtXT7E',
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
    director: 'Christopher Nolan',
    platforms: ['Paramount+', 'Prime Video'],
    isHiddenGem: false,
    popularityScore: 91,
    language: 'en',
  },
  {
    id: 76341,
    title: 'Mad Max: Fury Road',
    year: 2015,
    rating: 8.1,
    voteCount: 1100000,
    duration: 120,
    genres: ['Action', 'Adventure', 'Science Fiction'],
    moods: ['adventurous', 'thrilled'],
    synopsis:
      'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search of her homeland with the aid of a group of female prisoners.',
    posterPath: '/hA2ple9q4qnwxp3hKVNhroipsir.jpg',
    trailerKey: 'hEJnMQG9ev8',
    cast: ['Tom Hardy', 'Charlize Theron', 'Nicholas Hoult'],
    director: 'George Miller',
    platforms: ['Max', 'Netflix'],
    isHiddenGem: false,
    popularityScore: 83,
    language: 'en',
  },
  {
    id: 281957,
    title: 'The Revenant',
    year: 2015,
    rating: 8.0,
    voteCount: 1000000,
    duration: 156,
    genres: ['Adventure', 'Drama', 'Western'],
    moods: ['adventurous', 'dark', 'emotional'],
    synopsis:
      'A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear.',
    posterPath: '/ji3ecJphATlVgWNY0B0RVXZizdf.jpg',
    trailerKey: 'LoebZZ8K5N0',
    cast: ['Leonardo DiCaprio', 'Tom Hardy', 'Will Poulter'],
    director: 'Alejandro González Iñárritu',
    platforms: ['Disney+', 'Prime Video'],
    isHiddenGem: false,
    popularityScore: 80,
    language: 'en',
  },
  {
    id: 58,
    title: 'Indiana Jones and the Raiders of the Lost Ark',
    year: 1981,
    rating: 8.4,
    voteCount: 850000,
    duration: 115,
    genres: ['Action', 'Adventure'],
    moods: ['adventurous', 'playful', 'nostalgic'],
    synopsis:
      'Archaeologist and adventurer Indiana Jones is hired by the US government to find the Ark of the Covenant before the Nazis.',
    posterPath: '/ceG9VzoRAVGwivFU403Wc3AHRys.jpg',
    trailerKey: '0VGNQ-KSuSQ',
    cast: ['Harrison Ford', 'Karen Allen', 'Paul Freeman'],
    director: 'Steven Spielberg',
    platforms: ['Disney+', 'Paramount+'],
    isHiddenGem: false,
    popularityScore: 84,
    language: 'en',
  },

  // ── ROMANTIC ───────────────────────────────────────────────────────────────
  {
    id: 313369,
    title: 'La La Land',
    year: 2016,
    rating: 7.9,
    voteCount: 1200000,
    duration: 128,
    genres: ['Drama', 'Music', 'Romance'],
    moods: ['romantic', 'inspired', 'nostalgic', 'emotional'],
    synopsis:
      'While navigating their careers in Los Angeles, a pianist and an aspiring actress fall in love while attempting to reconcile their aspirations for the future.',
    posterPath: '/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg',
    trailerKey: '0pdqf4P9MB8',
    cast: ['Ryan Gosling', 'Emma Stone', 'John Legend'],
    director: 'Damien Chazelle',
    platforms: ['Netflix', 'Prime Video'],
    isHiddenGem: false,
    popularityScore: 87,
    language: 'en',
  },
  {
    id: 16538,
    title: 'Notting Hill',
    year: 1999,
    rating: 7.1,
    voteCount: 490000,
    duration: 124,
    genres: ['Comedy', 'Drama', 'Romance'],
    moods: ['romantic', 'playful'],
    synopsis:
      'The life of a simple bookshop owner changes when he meets the most famous film star in the world.',
    posterPath: '/rxqfMBe3kGnCrPMrLfJPVcUuBOu.jpg',
    trailerKey: 'PimxPNJSy8o',
    cast: ['Julia Roberts', 'Hugh Grant', 'Rhys Ifans'],
    director: 'Roger Michell',
    platforms: ['Netflix', 'Prime Video'],
    isHiddenGem: false,
    popularityScore: 67,
    language: 'en',
  },
  {
    id: 11449,
    title: 'Before Sunrise',
    year: 1995,
    rating: 8.1,
    voteCount: 380000,
    duration: 101,
    genres: ['Drama', 'Romance'],
    moods: ['romantic', 'emotional', 'nostalgic'],
    synopsis:
      'A young man and woman meet on a train in Europe, and wind up spending one evening together in Vienna. Unfortunately, both know that this will be their only night together.',
    posterPath: '/pSGXhpdmYpCFdurbs2D1EP7sONk.jpg',
    trailerKey: 'gKCVkV3bS9Q',
    cast: ['Ethan Hawke', 'Julie Delpy'],
    director: 'Richard Linklater',
    platforms: ['Max', 'Criterion Channel'],
    isHiddenGem: true,
    popularityScore: 72,
    language: 'en',
  },
  {
    id: 400535,
    title: 'Crazy Rich Asians',
    year: 2018,
    rating: 6.9,
    voteCount: 430000,
    duration: 120,
    genres: ['Comedy', 'Drama', 'Romance'],
    moods: ['romantic', 'playful'],
    synopsis:
      'A New Yorker accompanies her boyfriend to Singapore for his best friend\'s wedding, only to discover that he\'s from a wealthy family.',
    posterPath: '/lLN9L2vqAFNxSpGkiqibBsWNxFm.jpg',
    trailerKey: 'pNnaVqVWzJA',
    cast: ['Constance Wu', 'Henry Golding', 'Michelle Yeoh'],
    director: 'Jon M. Chu',
    platforms: ['Netflix', 'Max'],
    isHiddenGem: false,
    popularityScore: 74,
    language: 'en',
  },

  // ── INSPIRED ───────────────────────────────────────────────────────────────
  {
    id: 244786,
    title: 'Whiplash',
    year: 2014,
    rating: 8.5,
    voteCount: 900000,
    duration: 107,
    genres: ['Drama', 'Music'],
    moods: ['inspired', 'dark', 'emotional'],
    synopsis:
      'A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are pursued by an instructor who will stop at nothing to realize a student\'s potential.',
    posterPath: '/7fn624j5lj3xTme2SgiLCeuedmO.jpg',
    trailerKey: '7d_jQycdQGo',
    cast: ['Miles Teller', 'J.K. Simmons', 'Paul Reiser'],
    director: 'Damien Chazelle',
    platforms: ['Netflix', 'Prime Video'],
    isHiddenGem: false,
    popularityScore: 86,
    language: 'en',
  },
  {
    id: 37799,
    title: 'The Social Network',
    year: 2010,
    rating: 7.8,
    voteCount: 870000,
    duration: 120,
    genres: ['Drama', 'History'],
    moods: ['inspired', 'curious', 'dark'],
    synopsis:
      'The story of Harvard student and computer programmer Mark Zuckerberg as he begins work on a new concept that eventually turns into the global social network known as Facebook.',
    posterPath: '/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg',
    trailerKey: 'lB95KLmpLR4',
    cast: ['Jesse Eisenberg', 'Andrew Garfield', 'Justin Timberlake'],
    director: 'David Fincher',
    platforms: ['Netflix', 'Prime Video'],
    isHiddenGem: false,
    popularityScore: 81,
    language: 'en',
  },
  {
    id: 1366,
    title: 'Rocky',
    year: 1976,
    rating: 7.9,
    voteCount: 510000,
    duration: 119,
    genres: ['Drama', 'Sport'],
    moods: ['inspired', 'emotional', 'nostalgic'],
    synopsis:
      'A small-time boxer gets a supremely rare chance to fight a heavy-weight champion in a bout in which he strives to go the distance for his self-respect.',
    posterPath: '/xI0pkHj3nzSSUO9VqBhPOhSKMlm.jpg',
    trailerKey: 'grCgNGTu6Xk',
    cast: ['Sylvester Stallone', 'Talia Shire', 'Burt Young'],
    director: 'John G. Avildsen',
    platforms: ['Prime Video', 'Tubi'],
    isHiddenGem: false,
    popularityScore: 76,
    language: 'en',
  },
  {
    id: 205596,
    title: 'The Imitation Game',
    year: 2014,
    rating: 8.0,
    voteCount: 770000,
    duration: 113,
    genres: ['Drama', 'History', 'Biography'],
    moods: ['inspired', 'emotional', 'curious'],
    synopsis:
      'During World War II, mathematician Alan Turing tries to crack the enigma code with help from fellow mathematicians while navigating homophobia.',
    posterPath: '/zSqJ1qFq8NXFfi7JeIYMlzyR0dx.jpg',
    trailerKey: 'j2jRs4EAvWM',
    cast: ['Benedict Cumberbatch', 'Keira Knightley', 'Matthew Goode'],
    director: 'Morten Tyldum',
    platforms: ['Netflix', 'Prime Video'],
    isHiddenGem: false,
    popularityScore: 79,
    language: 'en',
  },
  {
    id: 381288,
    title: 'Hidden Figures',
    year: 2016,
    rating: 7.8,
    voteCount: 390000,
    duration: 127,
    genres: ['Drama', 'History', 'Biography'],
    moods: ['inspired', 'emotional'],
    synopsis:
      'The story of a team of female African-American mathematicians who served a vital role in NASA during the early years of the US space program.',
    posterPath: '/tPBo7tBi4KaxRhqBD9eSdtZPPeQ.jpg',
    trailerKey: 'RK8xkvfrUTA',
    cast: ['Taraji P. Henson', 'Octavia Spencer', 'Janelle Monáe'],
    director: 'Theodore Melfi',
    platforms: ['Disney+', 'Prime Video'],
    isHiddenGem: false,
    popularityScore: 75,
    language: 'en',
  },

  // ── NOSTALGIC ──────────────────────────────────────────────────────────────
  {
    id: 105,
    title: 'Back to the Future',
    year: 1985,
    rating: 8.5,
    voteCount: 1100000,
    duration: 116,
    genres: ['Adventure', 'Comedy', 'Science Fiction'],
    moods: ['nostalgic', 'adventurous', 'playful'],
    synopsis:
      'Marty McFly, a 17-year-old high school student, is accidentally sent thirty years into the past in a time-traveling DeLorean.',
    posterPath: '/fNOH9f1aA7XRTzl1sAOx9iF553Q.jpg',
    trailerKey: 'qvsgGtivCgs',
    cast: ['Michael J. Fox', 'Christopher Lloyd', 'Lea Thompson'],
    director: 'Robert Zemeckis',
    platforms: ['Peacock', 'Prime Video'],
    isHiddenGem: false,
    popularityScore: 87,
    language: 'en',
  },
  {
    id: 601,
    title: 'E.T. the Extra-Terrestrial',
    year: 1982,
    rating: 7.9,
    voteCount: 700000,
    duration: 115,
    genres: ['Family', 'Science Fiction', 'Adventure'],
    moods: ['nostalgic', 'emotional', 'adventurous'],
    synopsis:
      'A lonely boy befriends a gentle alien that is stranded on Earth and tries to help the creature return home.',
    posterPath: '/an0nD6uq6byfxXCfk6liqyFvZEy.jpg',
    trailerKey: 'qYAETtIIClk',
    cast: ['Henry Thomas', 'Drew Barrymore', 'Peter Coyote'],
    director: 'Steven Spielberg',
    platforms: ['Peacock', 'Prime Video'],
    isHiddenGem: false,
    popularityScore: 80,
    language: 'en',
  },
  {
    id: 771,
    title: 'Home Alone',
    year: 1990,
    rating: 7.4,
    voteCount: 780000,
    duration: 103,
    genres: ['Comedy', 'Family'],
    moods: ['nostalgic', 'playful'],
    synopsis:
      'An 8-year-old boy is accidentally left behind when his family flies to France for Christmas, and must defend their home from burglars.',
    posterPath: '/onTSipZ8R3bliBdKfPtsDskipcr.jpg',
    trailerKey: 'SYomU7SgJXo',
    cast: ['Macaulay Culkin', 'Joe Pesci', 'Daniel Stern'],
    director: 'Chris Columbus',
    platforms: ['Disney+'],
    isHiddenGem: false,
    popularityScore: 82,
    language: 'en',
  },
  {
    id: 9377,
    title: "Ferris Bueller's Day Off",
    year: 1986,
    rating: 7.9,
    voteCount: 450000,
    duration: 103,
    genres: ['Comedy', 'Drama'],
    moods: ['nostalgic', 'playful', 'relaxed'],
    synopsis:
      'A high school wise guy is determined to have a day off from school, despite the best efforts of his principal.',
    posterPath: '/p7JpBXXnbBBdlATXTbH2Zpcrg2p.jpg',
    trailerKey: 'dMBl5W7ZKEE',
    cast: ['Matthew Broderick', 'Alan Ruck', 'Mia Sara'],
    director: 'John Hughes',
    platforms: ['Peacock', 'Prime Video'],
    isHiddenGem: false,
    popularityScore: 79,
    language: 'en',
  },

  // ── CURIOUS ────────────────────────────────────────────────────────────────
  {
    id: 329865,
    title: 'Arrival',
    year: 2016,
    rating: 7.9,
    voteCount: 780000,
    duration: 116,
    genres: ['Drama', 'Mystery', 'Science Fiction'],
    moods: ['curious', 'emotional', 'adventurous'],
    synopsis:
      'When twelve mysterious spacecraft appear around the world, a linguistics professor is recruited by the military to determine whether alien life forms are visiting in peace or are a threat.',
    posterPath: '/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg',
    trailerKey: 'tFMo3UJ4B4g',
    cast: ['Amy Adams', 'Jeremy Renner', 'Forest Whitaker'],
    director: 'Denis Villeneuve',
    platforms: ['Paramount+', 'Prime Video'],
    isHiddenGem: false,
    popularityScore: 82,
    language: 'en',
  },
  {
    id: 27205,
    title: 'Inception',
    year: 2010,
    rating: 8.8,
    voteCount: 2200000,
    duration: 148,
    genres: ['Action', 'Adventure', 'Science Fiction', 'Thriller'],
    moods: ['curious', 'thrilled', 'adventurous'],
    synopsis:
      'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    posterPath: '/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
    trailerKey: 'YoHD9XEInc0',
    cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page'],
    director: 'Christopher Nolan',
    platforms: ['Max', 'Prime Video'],
    isHiddenGem: false,
    popularityScore: 94,
    language: 'en',
  },
  {
    id: 546554,
    title: 'Knives Out',
    year: 2019,
    rating: 7.9,
    voteCount: 860000,
    duration: 130,
    genres: ['Crime', 'Drama', 'Mystery', 'Comedy'],
    moods: ['curious', 'playful', 'thrilled'],
    synopsis:
      'The circumstances surrounding the death of crime novelist Harlan Thrombey are investigated by Detective Benoit Blanc.',
    posterPath: '/pThyQovXQrws2hmkal2dZE3qg1p.jpg',
    trailerKey: 'qGqiHJTsRkQ',
    cast: ['Daniel Craig', 'Chris Evans', 'Ana de Armas'],
    director: 'Rian Johnson',
    platforms: ['Prime Video', 'Netflix'],
    isHiddenGem: false,
    popularityScore: 84,
    language: 'en',
  },
  {
    id: 37686,
    title: 'Memento',
    year: 2000,
    rating: 8.4,
    voteCount: 1100000,
    duration: 113,
    genres: ['Mystery', 'Thriller'],
    moods: ['curious', 'dark', 'thrilled'],
    synopsis:
      'A man with short-term memory loss attempts to track down his wife\'s murderer using tattoos and polaroid notes to navigate his disability.',
    posterPath: '/yuNs09hvpHVU1cBTCAk9zxsL2oW.jpg',
    trailerKey: '4CV41hB_MZA',
    cast: ['Guy Pearce', 'Carrie-Anne Moss', 'Joe Pantoliano'],
    director: 'Christopher Nolan',
    platforms: ['Max', 'Prime Video'],
    isHiddenGem: false,
    popularityScore: 83,
    language: 'en',
  },
  {
    id: 166428,
    title: 'Coherence',
    year: 2013,
    rating: 7.2,
    voteCount: 110000,
    duration: 88,
    genres: ['Science Fiction', 'Mystery', 'Thriller'],
    moods: ['curious', 'thrilled', 'dark'],
    synopsis:
      'Strange things begin to happen when a group of friends gather for a dinner party on an evening when a comet passes overhead.',
    posterPath: '/hz7pBD8hHpXRHwSyNwlQIIeGRSv.jpg',
    trailerKey: 'fbTRd2tYnm8',
    cast: ['Emily Foxler', 'Maury Sterling', 'Nicholas Brendon'],
    director: 'James Ward Byrkit',
    platforms: ['Tubi', 'Prime Video'],
    isHiddenGem: true,
    popularityScore: 55,
    language: 'en',
  },

  // ── DARK ───────────────────────────────────────────────────────────────────
  {
    id: 550,
    title: 'Fight Club',
    year: 1999,
    rating: 8.8,
    voteCount: 2100000,
    duration: 139,
    genres: ['Drama', 'Thriller'],
    moods: ['dark', 'thrilled', 'curious'],
    synopsis:
      'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.',
    posterPath: '/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
    trailerKey: 'SUXWAEX2jlg',
    cast: ['Brad Pitt', 'Edward Norton', 'Helena Bonham Carter'],
    director: 'David Fincher',
    platforms: ['Max', 'Prime Video'],
    isHiddenGem: false,
    popularityScore: 91,
    language: 'en',
  },
  {
    id: 168259,
    title: 'No Country for Old Men',
    year: 2007,
    rating: 8.2,
    voteCount: 860000,
    duration: 122,
    genres: ['Crime', 'Drama', 'Thriller'],
    moods: ['dark', 'thrilled', 'curious'],
    synopsis:
      'A hunter in Texas stumbles upon a drug deal gone wrong and takes the money. But he is then pursued by a relentless killer, while an old sheriff tries to make sense of the violence.',
    posterPath: '/6d5XOczc2bNeFuZukkUzHnVGSCI.jpg',
    trailerKey: '38A__WT3-o0',
    cast: ['Tommy Lee Jones', 'Javier Bardem', 'Josh Brolin'],
    director: 'Joel Coen, Ethan Coen',
    platforms: ['Max', 'Prime Video'],
    isHiddenGem: false,
    popularityScore: 82,
    language: 'en',
  },
  {
    id: 496243,
    title: 'Parasite',
    year: 2019,
    rating: 8.5,
    voteCount: 1200000,
    duration: 132,
    genres: ['Comedy', 'Drama', 'Thriller'],
    moods: ['dark', 'curious', 'thrilled'],
    synopsis:
      'All unemployed, Ki-taek\'s family takes a peculiar interest in the wealthy and glamorous Park family and begins to infiltrate their household.',
    posterPath: '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    trailerKey: '5xH0HfJHsaY',
    cast: ['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong'],
    director: 'Bong Joon-ho',
    platforms: ['Max', 'Prime Video'],
    isHiddenGem: false,
    popularityScore: 89,
    language: 'ko',
  },
  {
    id: 76203,
    title: 'Black Swan',
    year: 2010,
    rating: 7.9,
    voteCount: 820000,
    duration: 108,
    genres: ['Drama', 'Thriller'],
    moods: ['dark', 'thrilled', 'inspired'],
    synopsis:
      'A committed dancer struggles to maintain her sanity after winning the lead role in a production of Tchaikovsky\'s "Swan Lake".',
    posterPath: '/nBNCB3F44idQ0HiHJBJbKMoqXSB.jpg',
    trailerKey: '5jaI9B8PnBc',
    cast: ['Natalie Portman', 'Mila Kunis', 'Vincent Cassel'],
    director: 'Darren Aronofsky',
    platforms: ['Disney+', 'Prime Video'],
    isHiddenGem: false,
    popularityScore: 80,
    language: 'en',
  },
  {
    id: 73984,
    title: 'American History X',
    year: 1998,
    rating: 8.5,
    voteCount: 1100000,
    duration: 119,
    genres: ['Drama', 'Crime'],
    moods: ['dark', 'emotional', 'inspired'],
    synopsis:
      'A former neo-nazi skinhead tries to prevent his younger brother from going down the same wrong path that he did.',
    posterPath: '/5FBfOH1Kc55RQOdpGjJMlLQjfxs.jpg',
    trailerKey: 'ZzPVZSNBG5g',
    cast: ['Edward Norton', 'Edward Furlong', 'Beverly D\'Angelo'],
    director: 'Tony Kaye',
    platforms: ['Netflix', 'Max'],
    isHiddenGem: false,
    popularityScore: 82,
    language: 'en',
  },

  // ── HIDDEN GEMS ────────────────────────────────────────────────────────────
  {
    id: 294272,
    title: 'Hunt for the Wilderpeople',
    year: 2016,
    rating: 7.9,
    voteCount: 160000,
    duration: 101,
    genres: ['Comedy', 'Adventure', 'Drama'],
    moods: ['relaxed', 'playful', 'emotional', 'adventurous'],
    synopsis:
      'A national manhunt is ordered for a rebellious kid and his foster uncle who go missing in the New Zealand bush.',
    posterPath: '/4mGMFP4ZXqVB2nQCHlpbdx6kxhH.jpg',
    trailerKey: 'pq7EVjPCacs',
    cast: ['Sam Neill', 'Julian Dennison', 'Rima Te Wiata'],
    director: 'Taika Waititi',
    platforms: ['Hulu', 'Prime Video'],
    isHiddenGem: true,
    popularityScore: 58,
    language: 'en',
  },
  {
    id: 18710,
    title: 'The Fall',
    year: 2006,
    rating: 7.9,
    voteCount: 90000,
    duration: 117,
    genres: ['Drama', 'Adventure', 'Fantasy'],
    moods: ['curious', 'emotional', 'dark', 'nostalgic'],
    synopsis:
      'In a hospital on the outskirts of 1920s Los Angeles, an injured stuntman begins to tell a fellow patient a fantastical story.',
    posterPath: '/oDNsz5bB7lBNI0qE6a4leBzOGHH.jpg',
    trailerKey: 'a7j1iiMV5p0',
    cast: ['Lee Pace', 'Catinca Untaru', 'Justine Waddell'],
    director: 'Tarsem Singh',
    platforms: ['Tubi', 'Prime Video'],
    isHiddenGem: true,
    popularityScore: 48,
    language: 'en',
  },
  {
    id: 103902,
    title: 'The Way Way Back',
    year: 2013,
    rating: 7.4,
    voteCount: 88000,
    duration: 103,
    genres: ['Comedy', 'Drama'],
    moods: ['relaxed', 'emotional', 'nostalgic'],
    synopsis:
      'Shy, 14-year-old Duncan goes on a summer holiday to a beach house with his reluctant mother and her overbearing boyfriend. Finding an unlikely mentor, he takes a job at a water park.',
    posterPath: '/1K2sxMgQbhOi2gF00Z48F2VqPMJ.jpg',
    trailerKey: 'E27fGkRCEF0',
    cast: ['Liam James', 'Steve Carell', 'Toni Collette'],
    director: 'Nat Faxon',
    platforms: ['Prime Video'],
    isHiddenGem: true,
    popularityScore: 52,
    language: 'en',
  },
  {
    id: 68716,
    title: 'About Time',
    year: 2013,
    rating: 7.8,
    voteCount: 390000,
    duration: 123,
    genres: ['Comedy', 'Drama', 'Romance', 'Science Fiction'],
    moods: ['romantic', 'emotional', 'relaxed'],
    synopsis:
      'At the age of 21, Tim discovers he can travel in time and goes back in time to change his love life, but soon finds that his decisions have unexpected consequences.',
    posterPath: '/h1QKQSVpH1MSM2MFPOcNLMYC6BV.jpg',
    trailerKey: 'b5jEBT2jVKM',
    cast: ['Domhnall Gleeson', 'Rachel McAdams', 'Bill Nighy'],
    director: 'Richard Curtis',
    platforms: ['Netflix', 'Prime Video'],
    isHiddenGem: true,
    popularityScore: 65,
    language: 'en',
  },
]

// ─── Helper Functions ─────────────────────────────────────────────────────────

export const TMDB_IMAGE_BASE = 'https://image.tmdb.org/t/p/w500'
export const TMDB_BACKDROP_BASE = 'https://image.tmdb.org/t/p/original'

export function getPosterUrl(posterPath: string): string {
  return `${TMDB_IMAGE_BASE}${posterPath}`
}

export function getYouTubeEmbedUrl(key: string): string {
  return `https://www.youtube.com/embed/${key}?autoplay=1&mute=0`
}

export function getMovieById(id: number): Movie | undefined {
  return MOCK_MOVIES.find((m) => m.id === id)
}

export function getTrendingMovies(limit = 10): Movie[] {
  return [...MOCK_MOVIES]
    .sort((a, b) => b.popularityScore - a.popularityScore)
    .slice(0, limit)
}

export function getMoviesByMood(mood: string): Movie[] {
  return MOCK_MOVIES.filter((m) => m.moods.includes(mood as never))
}

export const ALL_GENRES = Array.from(
  new Set(MOCK_MOVIES.flatMap((m) => m.genres))
).sort()

export const ALL_PLATFORMS = Array.from(
  new Set(MOCK_MOVIES.flatMap((m) => m.platforms))
).sort()
